version: '3'
services:
  website:
    image: php:7.2-apache
    volumes:
      - ./website:/var/www/html
    links:
      - myapi
    environment:
      USERNAME: toto
      PASSWORD: python
    restart: always
  myapi:
    image: python:2.7-stretch
    ports:
      - 5000:5000
    volumes:
      - ./website/simple_api/student_age.json:/data/student_age.json
    restart: always
